### ISSUE TITLE
Initial load tests on EPP

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#107]
# Description

To understand load and performance characteristics for launch, we should do some initial load testing and get an understanding of what load we can expect to serve

Note: we expect the journal infrastructure to add a layer of caching, so overall load after going live should be quite manageable.

# Tasks

- [ ] Perform an initial test (using ab or similar)
- [ ] Report performance to team and decide if any further action is required

# Definition of Done

- [ ] Performance understand
- [ ] Follow on action tickets (if required) are created and prioritised

**Comment by scottaubrey** [comment]
Initial load testing at 25 concurrency, about 50 requests in the service starts to 500 error. The culprit seems to be the hypothesis load on society, something they warned us about (see https://github.com/elifesciences/enhanced-preprints-server/issues/413)

Due to the slowness of those API requests, each page load is > 1s

**Comment by scottaubrey** [comment]
After adding caching to both EPP and Sciety, reran the test and didn't hit the 500 error wall again.

At higher concurrency, we seem to have an issue with the client dropping connections to APIs, like so
```
FetchError: request to http://epp-server:3000/api/reviewed-preprints/10.1101/2022.06.24.497502/reviews failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/opt/epp-client/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:481:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

At first I thought this was because the server was restarted as the extra load made the readiness probe fail and k8s would restart the pod. Giving this a longer timeout however didn't help. 

I've increased the number of client replicas and it seems to allow for higher concurrency without as many failures, but is still quite intermittent. Additionally the cluster's seems a bit full, so we might need to consider increasing the nodes available in the cluster.

Going with 3 client instances for launch.

I've also increased the number of nodes available to allow us to scale up the number of client-servers if/when we need it.
