### ISSUE TITLE
Rethink routes for journal

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#110]
# Description

As we're now exposing the /reviewed-preprints/ URL on the journal, we cannot rely on any resources exposed on other paths, most notably the CSS and JS bundles (available on `/_next`). Additionally, the first 

# Potential solutions:

1. Move all paths to the base `/`, so `/12345` and `/_next` resolves.
2. Move all paths to `/reviewed-preprints/` so `/reviewed-preprints/12345` and `/reviewed-preprints/_next` resolve.

# Chosen solution

I think we should go with 2, at least for launch, as that will give us the behaviour we want for journal. It does, however, take a step back as a general platform, as '/' now doesn't resolve to anything. @QueenKraken 

# Tasks

- [x] Update https://github.com/elifesciences/enhanced-preprints-client to publish to /reviewed-preprints 
  - https://github.com/elifesciences/enhanced-preprints-client/pull/111
- [x] Update Journal proxy config to pass URLs unnormalised
- [x] Create a ticket for any post-launch follow up actions

**Comment by scottaubrey** [comment]
@will-byrne @nlisgo FYI

**Comment by scottaubrey** [comment]
Also see  https://github.com/elifesciences/issues/issues/7773#issuecomment-1274237458
