### ISSUE TITLE
Build image of EPP client

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#17]
# Description

We need to build a docker image to start deploying the client. 

# Tasks

- [ ] Create a `Dockerfile` for the react client (based on `yarn build` output and nginx)
- [ ] Create a Makefile to handle building, tagging and pushing images to a container repo
- [ ] Create a GH workflow to invoke the Makefile and push to ghcr.io
