### ISSUE TITLE
Build image of EPP storybook

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#18]
# Description

It would be good to showcase the EPP client components as a pattern library using storybook. Build an container image that contains our components and storybook setup.

# Tasks

- [ ] Create a `Dockerfile` for the for the client code with `yarn storybook` as the command
- [ ] Create a Makefile to handle building, tagging and pushing images to a container repo
- [ ] Create a GH workflow to invoke the Makefile and push to ghcr.io
