### ISSUE TITLE
Implement the overall design of EPP in EPP-client

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#61]
# Description

We want to be ready to showcase the EPP platform to the world to match the desired designs. This Epic tracks work towards the goal of matching the EPP platform the latest designs [here](https://miro.com/app/board/uXjVOgOZ7BQ=/)

# Tasks
- [x] https://github.com/elifesciences/enhanced-preprints-client/issues/56
- [x] #58 
- [x] https://github.com/elifesciences/enhanced-preprints-client/issues/78
- [x] https://github.com/elifesciences/enhanced-preprints-client/issues/50
