### ISSUE TITLE
Improve article rendering for October launch (Sprint 58)

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#62]
# Description

While the value in launching in October should be focussed on how we present preprint articles and communicate their value, we do not want the quality of preprint rendering to distract from that. This Epic tracks any improvements to Encoda rendering that should be prioritsed for October

# Tasks

- [x] #57 
- [x] #42 
- [x] https://github.com/elifesciences/enhanced-preprints-server/issues/326
- [x] https://github.com/elifesciences/enhanced-preprints-client/issues/63
- [x] https://github.com/elifesciences/enhanced-preprints-client/issues/26
- [x] #55 
- [x] https://github.com/elifesciences/enhanced-preprints-client/issues/70
