### ISSUE TITLE
Changes to html/css and accessibility

### ISSUE THREAD

**Issue by discodavey** [elifesciences/enhanced-preprints-client#84]
# Description

There are various small items that need to be changed and would rather group them together rather than individual tickets. This is the first pass and there will be further changes but these will done when the project progresses.

# Subtasks

- [x] Add text to eLife logo and use text indent (and refactor code)
- [x] Content attribute in h1 to be removed as not needed
- [x] Authors list needs aria label
- [x] Affiliations list needs aria label
- [x] Paragraph in secondary column should be a paragraph tag not a span
- [x] Article actions in secondary column to be a list either ul or ol
- [x] Jump menu should be in a nav tag
- [x] Class primary-column should be a div
- [x] Main-content-area should be in a main tag
- [x] Swap content header div to be header tag
- [x] Move article-furniture class to same div as secondary column div

# Definition of Done

- [ ] When the above tasks have been completed

**Comment by QueenKraken** [comment]
@discodavey not sure if you want this in the sprint or part of your 15%. Let me know so I can prioritise it :)

**Comment by discodavey** [comment]
The (15%)10% day is for learning. The work above is not really learning as it's refactoring the code.

**Comment by QueenKraken** [comment]
Ok, will add as part of the tech debt sprint.

**Comment by discodavey** [comment]
Going to close this ticket. Add text to eLife logo I have put into a separate ticket
https://github.com/elifesciences/enhanced-preprints-client/issues/213
